Add Ashwin Dhangar to Contributor List
amyyalex/simple-contribution pull request #16
Opened 2023-11-11 17:40 UTC by MrAshwin2142

Thank you for give us chance to contribute in this project..

2023-11-12 22:40 UTC, amyyalex requested changes
Hi Ashwin, Thank you for your contribution. Before I merge, I will kindly ask that you add a new object into array in the app.js file instead of the index.html file. 
Thank you!

2023-11-13 02:21 UTC, MrAshwin2142 commented
Done @amyyalex

2023-11-16 09:47 UTC, amyyalex reviewed
Thank you! x

2023-11-16 09:48 UTC, amyyalex approved these changes

2023-11-16 09:51 UTC, merged